language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

env:
  - PROFILES=it-skip
  - PROFILES=!it-skip,it-wildfly-11.0.0-managed,code-quality
  - PROFILES=!it-skip,it-wildfly-11.0.0-embedded
  - PROFILES=!it-skip,it-wildfly-10.1.0-managed
  - PROFILES=!it-skip,it-wildfly-10.1.0-embedded
  - PROFILES=!it-skip,it-wildfly-10.1.0-embedded
  - PROFILES=!it-skip,it-glassfish-5.0-managed
  - PROFILES=!it-skip,it-glassfish-5.0-embedded
  - PROFILES=!it-skip,it-glassfish-4.1.2-managed
  - PROFILES=!it-skip,it-glassfish-4.1.2-embedded
  - PROFILES=!it-skip,it-tomee-7.0.4-managed
  - PROFILES=!it-skip,it-tomee-7.0.4-embedded

#  https://issues.jboss.org/browse/ARQ-2155

#addons:
#  sonarcloud:
#    organization: "javaee-design-patterns"
#    token:
#      secure: $SONAR_CLOUD_TOKEN
#script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P $PROFILES

script:
  - mvn test integration-test verify -B -P $PROFILES
