language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

env:
  - PROFILES=!coveralls-deploy,it-skip
  - PROFILES=!it-skip,it-wildfly-11.0.0-managed,code-quality
  - PROFILES=!coveralls-deploy,!it-skip,it-wildfly-11.0.0-embedded
  - PROFILES=!coveralls-deploy,!it-skip,it-wildfly-10.1.0-managed
  - PROFILES=!coveralls-deploy,!it-skip,it-wildfly-10.1.0-embedded
  - PROFILES=!coveralls-deploy,!it-skip,it-wildfly-10.1.0-embedded
  - PROFILES=!coveralls-deploy,!it-skip,it-glassfish-5.0-managed
  - PROFILES=!coveralls-deploy,!it-skip,it-glassfish-5.0-embedded
  - PROFILES=!coveralls-deploy,!it-skip,it-glassfish-4.1.2-managed
  - PROFILES=!coveralls-deploy,!it-skip,it-glassfish-4.1.2-embedded
  - PROFILES=!coveralls-deploy,!it-skip,it-tomee-7.0.4-managed
  - PROFILES=!coveralls-deploy,!it-skip,it-tomee-7.0.4-embedded

#  https://issues.jboss.org/browse/ARQ-2155

addons:
  sonarcloud:
    organization: "javaee-design-patterns"
    token:
      secure: $SONAR_CLOUD_TOKEN

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P $PROFILES

script:
  - mvn test integration-test verify install -B -P $PROFILES -Dcoveralls-token=$COVERALLS_REPO_TOKEN
