language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

env:
  - PROFILES=!sonar-deploy,!coveralls-deploy,it-skip
  - PROFILES=!sonar-deploy,!coveralls-deploy,!it-skip,it-wildfly-11.0.0-managed
  - PROFILES=!sonar-deploy,!coveralls-deploy,!it-skip,it-wildfly-11.0.0-embedded
  - PROFILES=!sonar-deploy,!coveralls-deploy,!it-skip,it-wildfly-10.1.0-managed
  - PROFILES=!sonar-deploy,!coveralls-deploy,!it-skip,it-wildfly-10.1.0-embedded
  - PROFILES=!sonar-deploy,!coveralls-deploy,!it-skip,it-wildfly-10.1.0-embedded
  - PROFILES=!sonar-deploy,!coveralls-deploy,!it-skip,it-glassfish-5.0-managed
  - PROFILES=!it-skip,it-glassfish-5.0-embedded,code-quality
  - PROFILES=!sonar-deploy,!coveralls-deploy,!it-skip,it-glassfish-4.1.2-managed
  - PROFILES=!sonar-deploy,!coveralls-deploy,!it-skip,it-glassfish-4.1.2-embedded
  - PROFILES=!sonar-deploy,!coveralls-deploy,!it-skip,it-tomee-7.0.4-managed
  - PROFILES=!sonar-deploy,!coveralls-deploy,!it-skip,it-tomee-7.0.4-embedded

#  https://issues.jboss.org/browse/ARQ-2155

install:
  - mvn clean install -B -V -P $PROFILES -Dcoveralls-token=$COVERALLS_REPO_TOKEN -Dsonar-token=$SONAR_CLOUD_TOKEN

#ignore default
script:
  - mvn --version
