language: java
jdk:
  - oraclejdk8

env:
  - CONTAINER=it-skip
  - CONTAINER=it-wildfly-11.0.0-managed
  - CONTAINER=it-wildfly-11.0.0-embedded
  - CONTAINER=it-wildfly-10.1.0-managed
  - CONTAINER=it-wildfly-10.1.0-embedded

#install: install any dependencies required
#script: run the build script
#deploy deploy

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P $CONTAINER

script:
  - mvn test integration-test verify -B -P $CONTAINER