language: java

dist: trusty

jdk:
  - oraclejdk8

addons:
   chrome: stable
   firefox: stable
   opera: stable

cache:
  directories:
  - $HOME/.m2

env:
  - PROFILES=it-skip
  - PROFILES=it-wildfly-11.0.0-managed,browser-chromeheadless
  - PROFILES=it-wildfly-11.0.0-embedded,browser-chromeheadless
  - PROFILES=it-wildfly-10.1.0-managed,browser-chromeheadless
  - PROFILES=it-wildfly-10.1.0-embedded,browser-chromeheadless
  - PROFILES=it-wildfly-10.1.0-embedded,browser-chromeheadless
  - PROFILES=it-glassfish-5.0-managed,browser-chromeheadless
  - PROFILES=it-glassfish-5.0-embedded,browser-chromeheadless
  - PROFILES=it-glassfish-4.1.2-managed,browser-chromeheadless
  - PROFILES=it-glassfish-4.1.2-embedded,browser-chromeheadless
  - PROFILES=it-tomee-7.0.4-managed,browser-chromeheadless
  - PROFILES=it-tomee-7.0.4-embedded,browser-chromeheadless
  - PROFILES=it-tomee-7.0.4-embedded,browser-chrome
  - PROFILES=it-tomee-7.0.4-embedded,browser-edge
  - PROFILES=it-tomee-7.0.4-embedded,browser-firefox
  - PROFILES=it-tomee-7.0.4-embedded,browser-opera
  - PROFILES=it-tomee-7.0.4-embedded,browser-phantomejs
  - PROFILES=it-tomee-7.0.4-embedded,browser-safari
  - PROFILES=it-glassfish-5.0-embedded,browser-chromeheadless,code-quality GOALS='org.sonarsource.scanner.maven:sonar-maven-plugin:sonar'

#  https://issues.jboss.org/browse/ARQ-2155
matrix:
  allow_failures:
    - env: PROFILES=!it-skip,it-wildfly-11.0.0-embedded
    - env: PROFILES=!it-skip,it-glassfish-4.1.2-managed

addons:
  sonarcloud:
    organization: "anton-tregubov-github"
    token: $SONAR_TOKEN

#download
install:
  - mvn clean install -B -V -P $PROFILES -DskipTests=true -Dmaven.javadoc.skip=true
#execute
script:
  - mvn verify $GOALS -B -V -P $PROFILES