language: java
jdk:
  - oraclejdk8

env:
  - CONTAINER=no
  - CONTAINER=wildfly-11.0.0-managed
  - CONTAINER=wildfly-11.0.0-embedded
  - CONTAINER=wildfly-10.1.0-managed
  - CONTAINER=wildfly-10.1.0-embedded
  - CONTAINER=wildfly-10.1.0-embedded
  - CONTAINER=glassfish-5.0-managed
  - CONTAINER=glassfish-5.0-embedded
  - CONTAINER=glassfish-4.1.2-managed
  - CONTAINER=glassfish-4.1.2-embedded

#  https://issues.jboss.org/browse/ARQ-2155

#install: install any dependencies required
#script: run the build script
#deploy deploy

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dit=$CONTAINER

script:
  - mvn test integration-test verify -B -P $CONTAINER